# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-ScanShare
version:      1.004
version_from: lib/Device/ScanShare.pm
installdirs:  site
requires:
    Carp:                          0
    File::Path:                    0
    File::Slurp:                   0
    Getopt::Std:                   0
    Smart::Comments:               0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
